// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPJiBDCMSwAxxC8DTTKofsxjZY7qHulBg',
    appId: '1:1049611145428:web:7eceb8acbf35f13c306b41',
    messagingSenderId: '1049611145428',
    projectId: 'potty-chronicles',
    authDomain: 'potty-chronicles.firebaseapp.com',
    storageBucket: 'potty-chronicles.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPjjj5LieWnyJNDYDM7RZDNDkmUDtmRm4',
    appId: '1:1049611145428:android:b8fcc92efc0c89d9306b41',
    messagingSenderId: '1049611145428',
    projectId: 'potty-chronicles',
    storageBucket: 'potty-chronicles.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCwB-ZSR-jCoz0enu24w1IzWLZkmuCA3w',
    appId: '1:1049611145428:ios:5f9f896575593767306b41',
    messagingSenderId: '1049611145428',
    projectId: 'potty-chronicles',
    storageBucket: 'potty-chronicles.appspot.com',
    iosBundleId: 'com.example.travelRoutes',
  );
}
